version: "3.9"
services:
  php:
    build: .
    container_name: php-server
    ports:
      - "8110:80"
    restart: on-failure
    working_dir: /var/www/html
    volumes:
      - ./php:/var/www/html
    stdin_open: true
    tty: true
  node:
    image: node:18
    container_name: node-server
    ports:
      - "8120:8120"
    restart: on-failure
    working_dir: /var/www
    volumes:
      - ./react:/var/www/
    stdin_open: true
    tty: true
    command: bash -c "npm install && npm start"

